server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/app_db # jdbc:postgresql://localhost:5432/postgres
    username: sa # postgres
    password: # postgres
    driver-class-name: org.h2.Driver # org.postgresql.Driver

mybatis:
  mapper-locations: classpath*:/mybatis/*Mapper.xml
  type-alias-package: io.github.smallintro.mybatis.model