CREATE TABLE IF NOT EXISTS T_PRODUCT (
PRODUCT_ID INTEGER PRIMARY KEY,
PRODUCT_NAME VARCHAR(32) NOT NULL,
PRODUCT_PRICE NUMERIC(5,2) NOT NULL,
PRODUCT_COUNT INTEGER NOT NULL
);

INSERT INTO t_product (product_id, product_name, product_price, product_count) values (100, 'Test100', 100.99, 100);
commit;